name: build

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Build
        run: |
          echo ${{ github.ref }}
          go get -u -v golang.org/x/lint/golint
          go get -u -v golang.org/x/lint/golint
          go mod tidy
          go get -u -v
          go mod download
          golint .
          export CI=1
          go test -covermode=count -coverprofile=coverage.out
          cat coverage.out | grep -v "main.go" > coverage.txt
          TOTAL_COVERAGE_FOR_CI_F=$(go tool cover -func coverage.txt | grep total | grep -Eo '[0-9]+.[0-9]+')
          echo "TOTAL_COVERAGE_FOR_CI_F: $TOTAL_COVERAGE_FOR_CI_F"
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o htm-node
          tar czf htm-node.linux.amd64.tgz htm-node

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::htm-node_$(date +"%Y.%m.%d_%H_%M")"

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            htm-node.linux.amd64.tgz
